DROP TABLE IF EXISTS Participer;
DROP TABLE IF EXISTS Loger;
DROP TABLE IF EXISTS Besoin_equipement_artiste;
DROP TABLE IF EXISTS Posseder;
DROP TABLE IF EXISTS Avoir;
DROP TABLE IF EXISTS Concert;
DROP TABLE IF EXISTS Salle;
DROP TABLE IF EXISTS Type_Salle;
DROP TABLE IF EXISTS Jouer;
DROP TABLE IF EXISTS Artiste;
DROP TABLE IF EXISTS Logement;
DROP TABLE IF EXISTS Equipement;
DROP TABLE IF EXISTS Style_musique;

