INSERT INTO Style_musique (id_style_musique, nom_style_musique) VALUES
(1, 'Rock'),
(2, 'Pop'),
(3, 'Hip-Hop'),
(4, 'Electro'),
(5, 'Jazz'),
(6, 'Classique'),
(7, 'Reggae'),
(8, 'Funk'),
(9, 'Rap'),
(10, 'Metal'),
(11, 'Punk'),
(12, 'Blues'),
(13, 'Country'),
(14, 'RnB'),
(15, 'Soul'),
(16, 'Disco'),
(17, 'Techno'),
(18, 'House'),
(19, 'Trance');


INSERT INTO Equipement (id_equipement, nom_equipement) VALUES
(1, 'Guitare électrique'),
(2, 'Batterie'),
(3, 'Synthétiseur'),
(4, 'Basse électrique'),
(5, 'Microphone'),
(6, 'Amplificateur'),
(7, 'Piano'),
(8, 'Saxophone'),
(9, 'Trompette'),
(10, 'Violon'),
(11, 'Harpe'),
(12, 'Flûte'),
(13, 'Clarinette'),
(14, 'Trombone'),
(15, 'Hautbois'),
(16, 'Cor'),
(17, 'Tuba'),
(18, 'Percussions'),
(19, 'Accordéon'),
(20, 'Harmonica'),
(21, 'Orgue'),
(22, 'Percussions électroniques'),
(23, 'Table de mixage'),
(24, 'Enceinte'),
(25, 'Lumière'),
(26, 'Machine à fumée'),
(27, 'Machine à bulles'),
(28, 'Machine à confettis'),
(29, 'Machine à neige'),
(30, 'Machine à brouillard'),
(31, 'Machine à CO2'),
(32, 'Machine à pyrotechnie'),
(33, 'Machine à étincelles'),
(34, 'Machine à flammes'),
(35, 'Machine à mousse'),
(36, 'Machine à vent'),
(37, 'Machine à pluie'),
(38, 'Machine à arc-en-ciel'),
(39, 'Machine à laser'),
(40, 'Machine à stroboscope'),
(41, 'Machine à boule à facettes'),
(42, 'Machine à miroir'),
(43, 'Machine à éclairage UV'),
(44, 'Machine à éclairage LED'),
(45, 'Machine à éclairage RGB'),
(46, 'Machine à éclairage DMX'),
(47, 'Machine à éclairage sans fil'),
(48, 'Machine à éclairage à batterie'),
(49, 'Machine à éclairage à énergie solaire'),
(50, 'Machine à éclairage à énergie éolienne'),
(51, 'Machine à éclairage à énergie hydraulique'),
(52, 'Machine à éclairage à énergie thermique'),
(53, 'Machine à éclairage à énergie nucléaire'),
(54, 'Machine à éclairage à énergie éolienne'),
(55, 'Machine à éclairage à énergie géothermique'),
(56, 'Machine à éclairage à énergie hydrogène');